### ISSUE TITLE
Mobile view and langswitcher

### ISSUE THREAD

**Issue by k1ngf15h3r** [tranduyhung/grav-skeleton-big-picture#1]
I love this theme!!! 

But are there any plans for a more mobile friendly view? Would be great if the animations and arrows are also in mobile view available. 

And are there any ideas, tips or plans for a Integration of the langswitcher in mobile view? Could integrate it on Desktop view but on mobile it is not so easy to make it look correctly. 

Have a look at https://jannis.hagels.net/en to see your great theme in action :)

**Comment by tranduyhung** [comment]
I'm glad to see that the theme I made is useful :) All kudos to HTML5 UP who designed this HTML template, I just converted it to a Grav theme.

There is no room for language links in this template. Maybe we let the links float at the bottom right corner so that they are always visible in both desktop and mobile views?

To show the arrows, you can search for

```
@media screen and (max-width: 736px)
    .main.style2 .button.anchored {
      display: none; }
```

in user/themes/big-picture/assets/css/main.css and change "none" to "inline". I will consider this change in future releases.

**Comment by k1ngf15h3r** [comment]
Changed the line but how can I let the links float at the button right corner? Can you tell me where I have to include the langswitcher partial so that is displayed there ;)

**Comment by k1ngf15h3r** [comment]
Fixed :) removed the class from the ul tag in partials/langswitcher.html.twig now the links are shown under the footer links in mobile and in the right corner on desktop view :) thank for your hints :+1:
